version: '3.9'

services:
  postgresql:
    image: ${DB_IMAGE}
    ports:
      - ${DB_PORT}:5432
    volumes:
      - /srv/bootcamp/team4/postgresql/data:/var/lib/postgresql/data
    networks:
      - team4
    environment:
      - POSTGRES_PASSWORD=family
      - POSTGRES_USER=family
      - POSTGRES_DB=family

  team4-service:
    image: "${APP_IMAGE}:${TAG}"
    ports:
      - ${APP_PORT}:8080
    networks:
      - team4
    depends_on:
      - postgresql
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
    environment:
      - JAVA_FLAGS="-Xmx500m -Dlogging.level.com.zaxxer.hikari.HikariConfig=DEBUG"
      - DB_URL=jdbc:postgresql://postgresql:5432/family
      - DB_USERNAME=family
      - DB_PASSWORD=family
      - APP_PORT=8080

volumes:
  postgresql-data:
    driver: local

networks:
  team4:
    attachable: true